name: Claude Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - ready_for_review          # draft -> ready
      - review_requested          # added individual reviewer
      - reopened                  # closed PR was reopened
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"
concurrency:
  # PR runs: use PR number so runs for the same PR serialize
  # workflow_run events (called by other workflows): include repo+branch
  # Fallback for push/branch/scheduled runs: use workflow name + branch/ref
  group: ${{
    github.event_name == 'pull_request' &&
      format('{0}-pr-{1}', github.workflow, github.event.pull_request.number)
      ||
    github.event_name == 'workflow_run' &&
      format('{0}-run-{1}-{2}', github.workflow, github.event.workflow_run.head_repository.full_name, github.event.workflow_run.head_branch)
      ||
    format('{0}-branch-{1}', github.workflow, github.ref_name || github.ref)
    }}
  cancel-in-progress: true

jobs:
  claude-review:
    # Skip fork PRs: CLAUDE_CODE_OAUTH_TOKEN is not available for pull_request events
    # from forks, which would cause the job to fail. Only run on PRs from the same repo.
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    # Optional: Also filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request with a focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Security implications
            - Performance considerations

            Note: The PR branch is already checked out in the current working directory.

            Use `gh pr comment` for top-level feedback summary.
            Use `mcp__github_inline_comment__create_inline_comment` to highlight specific code issues with inline comments on the relevant lines.
            Only post GitHub comments - don't submit review text as messages.
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Read,Glob,Grep"
